### PR TITLE
70 swipe between pages

### PR DESCRIPTION
**Pull request by aklt**

### CODE REVIEW

**Comment by aklt** [comment]
There is an issue of maintaining the currentPageIndex which I will fix

**Comment by rasmuserik** [comment]
Probably get the current page from the application db, instead of maintaining currentPageIndex. It is much easier if all state is in the db.

**Comment by aklt** [comment]
This pull request should now be good to merge.

Not sure why `lein kibit` fails, it runs on my machine.

**Comment by aklt** [comment]
Tested this on my galaxy s3 and it seems that HammerJs in the current configuration 
prevents vertical scrolling or makes it flaky.  I have tried some workarounds but without 
a good result.

**Pull request merged**
